# Generated by Django 5.0.2 on 2024-02-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, unique=True)),
                ('impact_level', models.CharField(blank=True, choices=[('L', 'Low Impact'), ('M', 'Moderate Impact'), ('H', 'High Impact')], max_length=1, null=True)),
                ('release_date', models.DateTimeField()),
                ('event_name', models.CharField(max_length=100)),
                ('forecast', models.CharField(blank=True, max_length=20, null=True)),
                ('previous', models.CharField(blank=True, max_length=20, null=True)),
                ('actual', models.CharField(blank=True, max_length=20, null=True)),
                ('outcome', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
