# Generated by Django 5.0.2 on 2024-02-25 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_level', models.CharField(choices=[('L', 'Low Impact'), ('M', 'Moderate Impact'), ('H', 'High Impact')], help_text='The impact level of the economic event.', max_length=1)),
                ('release_date', models.DateTimeField(help_text='The release date of the economic event.')),
                ('event_name', models.CharField(help_text='The name of the economic event.', max_length=100)),
                ('forecast', models.CharField(blank=True, help_text='The forecasted value of the economic event.', max_length=20, null=True)),
                ('actual', models.CharField(blank=True, help_text='The actual value of the economic event.', max_length=20, null=True)),
                ('outcome', models.CharField(help_text='The outcome of the economic event (positive, negative, neutral, unknown).', max_length=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.currency')),
            ],
        ),
    ]
